export interface Work {
  n: string;
  slug: string;
  title: string;
  client: string;
  kind: string;
  year: string;
  role: string;
  tags: string[];
  image: string;
  summary: string;
  body: string[];
  scope: string;
  collaborator?: string;
  url?: string;
  previews?: {
    desktop?: string;
    mobile?: string;
  };
}

export interface Service {
  n: string;
  slug: string;
  title: string;
  cat: string;
  desc: string;
  items: string[];
  longDesc: string;
  features: { title: string; desc: string }[];
  process: { step: string; title: string; desc: string }[];
  stats: { value: string; label: string }[];
  faq: { q: string; a: string }[];
  tools: string[];
  relatedServices: string[];
}

export interface Story {
  no: string;
  slug: string;
  title: string;
  sub: string;
  year: string;
  role: string;
  tags: string[];
  image: string;
  body: string[];
  client?: string;
}

export interface Scene {
  id: string;
  label: string;
  hash: string;
}

export interface PreviewData extends Work {
  x?: number;
  y?: number;
}

export type Project = (Work & { type: "work" }) | (Story & { type: "story" });

export function getProjectBySlug(slug: string): Project | undefined {
  const work = WORKS.find((w) => w.slug === slug);
  if (work) return { ...work, type: "work" };
  const story = STORIES.find((s) => s.slug === slug);
  if (story) return { ...story, type: "story" };
  return undefined;
}

export function getAllProjectSlugs(): string[] {
  return [...WORKS.map((w) => w.slug), ...STORIES.map((s) => s.slug)];
}

export function getAllProjects(): Project[] {
  return [
    ...WORKS.map((w) => ({ ...w, type: "work" as const })),
    ...STORIES.map((s) => ({ ...s, type: "story" as const })),
  ];
}

export function getAdjacentProjects(slug: string): { prev: Project | null; next: Project | null } {
  const all = WORKS.map((w) => ({ ...w, type: "work" as const }));
  const idx = all.findIndex((p) => p.slug === slug);
  if (idx === -1) return { prev: null, next: null };
  return {
    prev: idx > 0 ? all[idx - 1] : all[all.length - 1],
    next: idx < all.length - 1 ? all[idx + 1] : all[0],
  };
}

export const WORKS: Work[] = [
  {
    n: "01",
    slug: "velis-ltd",
    title: "Velis LTD",
    client: "Velis Ticaret LTD",
    kind: "Web Design · CMS",
    year: "2024",
    role: "Design / Development",
    collaborator: "Saiber",
    tags: ["WordPress", "SEO", "Multi-language", "CMS"],
    image: "story-01.jpg",
    summary: "Construction company corporate site with product catalog.",
    body: [
      "Velis LTD için 25 yılı aşkın sektör deneyimini yansıtan kurumsal bir web sitesi tasarladık. WordPress altyapısı üzerine ürün kataloğu, çok dilli yapı ve SEO optimizasyonu dahil.",
      "İnşaat ve imalat sektörüne yönelik profesyonel bir dijital kimlik oluşturduk. Responsive tasarım, hızlı yüklenme süreleri ve kolay içerik yönetimi ile müşterinin dijital varlığını güçlendirdik.",
    ],
    scope: "Web design, CMS, SEO",
    previews: {
      desktop: '/assets/previews/desktop/velis-ltd.webp',
      mobile: '/assets/previews/mobile/velis-ltd.webp',
    }
  },
  {
    n: "02",
    slug: "fur-crm",
    title: "FurCRM",
    client: "FurCRM",
    kind: "Web App · SaaS",
    year: "2026",
    role: "Product / Development",
    tags: ["Next.js", "CRM", "ERP", "SaaS"],
    image: "story-01.jpg",
    summary: "Advanced CRM for the furniture industry — accounts, invoicing, dealers, production tracking.",
    body: [
      "FurCRM, mobilya üreticileri için geliştirdiğimiz kapsamlı bir CRM ve cari yönetim sistemi. Ürün & varyant yönetimi, müşteri CRM'i, cari & finans takibi, teklif–sipariş–fatura akışı ve bayi yönetimi tek panelde birleşiyor.",
      "Üretim takip paneli, raporlama ekranı, personel ve prim & performans modülleriyle bir mobilya işletmesinin tüm operasyonunu kapsıyor. Kendi ürünümüz olarak geliştirdiğimiz bu sistem, sektöre özel SaaS ürünleştirme yetkinliğimizin en kapsamlı örneği.",
    ],
    scope: "SaaS product, CRM, finance management",
    url: "https://fur-crm.vercel.app/",
    previews: {
      desktop: '/assets/previews/desktop/fur-crm.webp',
      mobile: '/assets/previews/mobile/fur-crm.webp',
    },
  },
  {
    n: "03",
    slug: "bt-elevator",
    title: "BT Elevator",
    client: "BT Elevator",
    kind: "Web Design · SEO",
    year: "2023",
    role: "Design / Development",
    tags: ["Corporate", "Multi-language", "SEO", "Responsive"],
    image: "story-02.jpg",
    summary: "Multi-language elevator company website with SEO optimization.",
    body: [
      "BT Elevator için Eskişehir merkezli asansör firmasının kurumsal web sitesini tasarladık ve geliştirdik. Çok dilli yapı, SEO optimizasyonu ve modern tasarım anlayışıyla sektörde fark yaratan bir dijital varlık oluşturduk.",
      "Teknik SEO çalışmaları, schema markup ve performans optimizasyonu ile arama motorlarında üst sıralarda yer almayı hedefledik. Kurumsal kimliğe uygun, güven veren bir kullanıcı deneyimi sunduk.",
    ],
    scope: "Web design, SEO, multi-language",
    previews: {
      desktop: '/assets/previews/desktop/bt-elevator.webp',
      mobile: '/assets/previews/mobile/bt-elevator.webp',
    }
  },
  {
    n: "04",
    slug: "gel-gez-gor",
    title: "Gel Gez Gör",
    client: "Gel Gez Gör",
    kind: "Web App · Platform",
    year: "2025",
    role: "Full-stack / Design",
    tags: ["Next.js", "Platform", "Classifieds", "SEO"],
    image: "story-03.jpg",
    summary: "Free classifieds platform for North Cyprus with multiple categories.",
    body: [
      "KKTC'nin kapsamlı ücretsiz ilan platformu Gel Gez Gör'ü tasarladık ve geliştirdik. Emlak, araç, iş ilanları ve yemek kategorilerinde binlerce ilan barındıran dinamik bir platform kurduk.",
      "Kullanıcı dostu arayüz, gelişmiş filtreleme sistemi ve SEO optimizasyonu ile KKTC'nin en çok ziyaret edilen ilan sitelerinden biri haline gelmesini sağladık.",
    ],
    scope: "Web app, platform, SEO",
    previews: {
      desktop: '/assets/previews/desktop/gel-gez-gor.webp',
      mobile: '/assets/previews/mobile/gel-gez-gor.webp',
    }
  },
  {
    n: "05",
    slug: "nexos-investment",
    title: "Nexos Investment",
    client: "Nexos Investment",
    kind: "Web App · Full-Stack",
    year: "2026",
    role: "Design / Development / Deploy",
    tags: ["Next.js", "Supabase", "Google Maps", "i18n"],
    image: "story-04.jpg",
    summary: "Custom real estate listing & management system — maps, multi-language, automated PDF/PPT proposals.",
    body: [
      "Hazır temalar Nexos Investment'ın ihtiyaçlarını karşılamıyordu; Next.js, Supabase ve Vercel ile sıfırdan, ölçeklenebilir bir emlak ilan yönetim sistemi geliştirdik. Google Maps + Leaflet ile cluster'lı interaktif harita, çok dilli yapı ve ilan verisinden otomatik PDF/PowerPoint teklif üretimi tek sistemde birleşti.",
      "TipTap editörlü yönetim paneli, PWA/offline desteği, Zod doğrulama, Upstash rate-limit ve Playwright E2E testleriyle üretim kalitesinde bir platform teslim ettik — portfolyomuzun teknik zirvesi.",
    ],
    scope: "Full-stack app, admin panel, PWA, E2E tests",
    previews: {
      desktop: '/assets/previews/desktop/nexos-investment.webp',
      mobile: '/assets/previews/mobile/nexos-investment.webp',
    },
  },
  {
    n: "06",
    slug: "alp-sigorta",
    title: "Alp Sigorta",
    client: "Alp Sigorta",
    kind: "Web Design · Insurance",
    year: "2026",
    role: "Design / Development",
    tags: ["Corporate", "Insurance", "Responsive", "SEO"],
    image: "story-03.jpg",
    summary: "Insurance company corporate website with service catalog.",
    body: [
      "Alp Sigorta için sigorta hizmetlerini sergileyen, güven veren ve profesyonel bir kurumsal web sitesi tasarladık. Hizmet kataloğu, teklif formu ve müşteri bilgilendirme sayfaları ile kapsamlı bir dijital platform oluşturduk.",
      "Responsive tasarım, hızlı yüklenme süreleri ve SEO optimizasyonu ile potansiyel müşterilerin kolayca ulaşmasını sağladık.",
    ],
    scope: "Web design, corporate, SEO",
    previews: {
      desktop: '/assets/previews/desktop/alp-sigorta.webp',
      mobile: '/assets/previews/mobile/alp-sigorta.webp',
    },
  },
  {
    n: "07",
    slug: "pampas-investment",
    title: "Pampas Investment",
    client: "Pampas Investment",
    kind: "Web Design · Real Estate",
    year: "2023",
    role: "Design / Development",
    collaborator: "Saiber",
    tags: ["WordPress", "Real Estate", "Corporate", "KKTC"],
    image: "story-01.jpg",
    summary: "Real estate investment company website in North Cyprus.",
    body: [
      "Kuzey Kıbrıs Esentepe merkezli Pampas Investment için gayrimenkul yatırım ve satış odaklı kurumsal bir web sitesi geliştirdik. Proje portföyü, arazi detayları ve yatırımcı bilgilendirme sayfaları ile güçlü bir dijital varlık oluşturduk.",
      "SEO optimizasyonu, çok dilli yapı ve responsive tasarım ile uluslararası yatırımcılara ulaşmayı hedefledik. Emlak ilan entegrasyonları ve sosyal medya bağlantıları ile müşteri edinimini artırdık.",
    ],
    scope: "Web design, real estate, SEO",
    previews: {
      desktop: '/assets/previews/desktop/pampas-investment.webp',
      mobile: '/assets/previews/mobile/pampas-investment.webp',
    },
  },
  {
    n: "08",
    slug: "ambalaj-cini",
    title: "Ambalaj Cini",
    client: "Ambalaj Cini",
    kind: "E-commerce · Web",
    year: "2022",
    role: "Design / Development",
    tags: ["E-commerce", "Payment Integration", "WordPress", "WooCommerce"],
    image: "story-05.jpg",
    summary: "E-commerce packaging supplies store with payment integration.",
    body: [
      "Bilecik merkezli Ambalaj Cini için online ambalaj malzemeleri satış platformu geliştirdik. Ödeme entegrasyonu, ürün yönetimi ve stok takibi dahil kapsamlı bir e-ticaret altyapısı kurduk.",
      "Kullanıcı deneyimi odaklı tasarım, kolay sipariş akışı ve güvenli ödeme altyapısı ile müşterinin online satışlarını önemli ölçüde artırdık. 2022'den bu yana aktif olarak hizmet veriyor.",
    ],
    scope: "E-commerce, web design, payment",
  },
  {
    n: "09",
    slug: "ekh-yapi",
    title: "EKH Yapı",
    client: "EKH Yapı",
    kind: "Web Design · Construction",
    year: "2022",
    role: "Design / Development",
    collaborator: "Saiber",
    tags: ["WordPress", "Construction", "Corporate", "Portfolio"],
    image: "story-04.jpg",
    summary: "Construction company website with project portfolio.",
    body: [
      "EKH Yapı için inşaat ve müteahhitlik hizmetlerini sergileyen kurumsal bir web sitesi tasarladık. Tamamlanan ve devam eden projelerin portföyü, hizmet detayları ve referanslar ile sektörde güçlü bir dijital kimlik oluşturduk.",
      "Proje galerisi, iletişim formları ve mobil uyumlu tasarım ile müşteri edinimini kolaylaştırdık. WordPress altyapısı ile kolay içerik yönetimi sağladık.",
    ],
    scope: "Web design, construction, portfolio",
    previews: {
      desktop: '/assets/previews/desktop/ekh-yapi.webp',
      mobile: '/assets/previews/mobile/ekh-yapi.webp',
    },
  },
  {
    n: "10",
    slug: "radyo-juke",
    title: "Radyo Juke",
    client: "Radyo Juke",
    kind: "Web App · Entertainment",
    year: "2025",
    role: "Design / Development",
    collaborator: "Saiber",
    tags: ["Web App", "Streaming", "Entertainment", "Responsive"],
    image: "story-02.jpg",
    summary: "Online radio streaming platform with live broadcast.",
    body: [
      "Radyo Juke için canlı yayın akışı, program rehberi ve dinleyici etkileşimi sunan modern bir online radyo platformu geliştirdik. Kullanıcı dostu arayüz ve kesintisiz yayın deneyimi ile fark yarattık.",
      "Responsive tasarım ile mobil ve masaüstü cihazlarda sorunsuz dinleme deneyimi sağladık. Sosyal medya entegrasyonu ve paylaşım özellikleri ile dinleyici kitlesini genişlettik.",
    ],
    scope: "Web app, streaming, design",
    previews: {
      desktop: '/assets/previews/desktop/radyo-juke.webp',
      mobile: '/assets/previews/mobile/radyo-juke.webp',
    },
  },
  {
    n: "11",
    slug: "ozge-ozler",
    title: "Özge Özler",
    client: "Özge Özler",
    kind: "Web Design · Personal",
    year: "2021",
    role: "Design / Development",
    collaborator: "Saiber",
    tags: ["Portfolio", "Personal Brand", "Responsive", "SEO"],
    image: "story-03.jpg",
    summary: "Personal brand and portfolio website.",
    body: [
      "Özge Özler için kişisel markayı ön plana çıkaran, profesyonel ve şık bir portfolyo web sitesi tasarladık. Minimalist tasarım anlayışı ile içeriklerin öne çıkmasını sağladık.",
      "SEO optimizasyonu, hızlı yüklenme süreleri ve mobil uyumlu yapı ile güçlü bir dijital varlık oluşturduk.",
    ],
    scope: "Web design, portfolio, personal brand",
    previews: {
      desktop: '/assets/previews/desktop/ozge-ozler.webp',
      mobile: '/assets/previews/mobile/ozge-ozler.webp',
    },
  },
  {
    n: "12",
    slug: "rnv-trading",
    title: "RNV Trading",
    client: "RNV Trading",
    kind: "Web Design · Corporate",
    year: "2021",
    role: "Design / Development",
    collaborator: "Saiber",
    tags: ["Corporate", "Trading", "Multi-language", "SEO"],
    image: "story-04.jpg",
    summary: "Trading and import-export company corporate website.",
    body: [
      "RNV Trading için uluslararası ticaret ve ithalat-ihracat faaliyetlerini sergileyen kurumsal bir web sitesi geliştirdik. Profesyonel imaj, ürün kataloğu ve iş ortaklığı bilgileri ile güçlü bir dijital kimlik oluşturduk.",
      "Çok dilli yapı, SEO optimizasyonu ve modern tasarım ile global müşterilere ulaşmayı hedefledik.",
    ],
    scope: "Web design, corporate, trading",
    previews: {
      desktop: '/assets/previews/desktop/rnv-trading.webp',
      mobile: '/assets/previews/mobile/rnv-trading.webp',
    },
  },
  {
    n: "13",
    slug: "pinnacle-yatirim",
    title: "Pinnacle Yatırım",
    client: "Pinnacle Yatırım",
    kind: "Web Design · Real Estate",
    year: "2026",
    role: "Design / Development",
    collaborator: "Saiber",
    tags: ["Real Estate", "Investment", "Corporate", "KKTC"],
    image: "story-05.jpg",
    summary: "Real estate investment company website in North Cyprus.",
    body: [
      "Pinnacle Yatırım için Kuzey Kıbrıs gayrimenkul yatırım sektörüne yönelik profesyonel bir kurumsal web sitesi geliştirdik. Yatırım portföyü, proje detayları ve danışmanlık hizmetlerini sergileyen kapsamlı bir platform oluşturduk.",
      "Modern tasarım, SEO optimizasyonu ve mobil uyumlu yapı ile potansiyel yatırımcılara güçlü bir dijital deneyim sunduk.",
    ],
    scope: "Web design, real estate, investment",
    previews: {
      desktop: '/assets/previews/desktop/pinnacle-yatirim.webp',
      mobile: '/assets/previews/mobile/pinnacle-yatirim.webp',
    },
  },
  {
    n: "14",
    slug: "jet-transfer-cyprus",
    title: "Jet Transfer Cyprus",
    client: "Jet Transfer Cyprus",
    kind: "Web Design · Transportation",
    year: "2025",
    role: "Design / Development",
    collaborator: "Saiber",
    tags: ["Transportation", "Booking", "Responsive", "KKTC"],
    image: "story-01.jpg",
    summary: "Airport transfer and VIP transportation service website.",
    body: [
      "Jet Transfer Cyprus için havalimanı transfer ve VIP ulaşım hizmetlerini sunan profesyonel bir web sitesi geliştirdik. Online rezervasyon sistemi, rota bilgileri ve fiyat hesaplama araçları ile kullanıcı deneyimini ön plana çıkardık.",
      "Mobil uyumlu tasarım, WhatsApp entegrasyonu ve çok dilli yapı ile yerli ve yabancı turistlere kolayca ulaşmayı sağladık.",
    ],
    scope: "Web design, transportation, booking",
  },
  {
    n: "15",
    slug: "boon-fresh",
    title: "Boon Fresh",
    client: "Boon Fresh",
    kind: "Web Design · E-commerce",
    year: "2025",
    role: "Design / Development",
    collaborator: "Saiber",
    tags: ["E-commerce", "Food", "Responsive", "SEO"],
    image: "story-04.jpg",
    summary: "Fresh food and grocery delivery e-commerce platform.",
    body: [
      "Boon Fresh için taze gıda ve market ürünleri teslimat platformu geliştirdik. Ürün kataloğu, sipariş yönetimi ve teslimat takibi ile kapsamlı bir e-ticaret altyapısı kurduk.",
      "Kullanıcı dostu arayüz, hızlı sipariş akışı ve mobil uyumlu tasarım ile müşteri memnuniyetini ön plana çıkardık. SEO optimizasyonu ile organik trafik artışı sağladık.",
    ],
    scope: "Web design, e-commerce, delivery",
  },
  {
    n: "16",
    slug: "halas-exchange",
    title: "Halas Exchange",
    client: "Halas Exchange",
    kind: "Web Design · Finance",
    year: "2024",
    role: "Design / Development",
    collaborator: "Saiber",
    tags: ["Finance", "Exchange", "Corporate", "KKTC"],
    image: "story-05.jpg",
    summary: "Currency exchange company website with live rates.",
    body: [
      "Halas Exchange için döviz alım-satım hizmetlerini sunan, güvenilir ve profesyonel bir web sitesi geliştirdik. Canlı kur bilgileri, şube lokasyonları ve kurumsal bilgiler ile kapsamlı bir platform oluşturduk.",
      "Hızlı yüklenme süreleri, responsive tasarım ve SEO optimizasyonu ile müşterilerin kolayca ulaşmasını sağladık.",
    ],
    scope: "Web design, finance, corporate",
    previews: {
      desktop: '/assets/previews/desktop/halas-exchange.webp',
    },
  },
  {
    n: "17",
    slug: "arslan-estates",
    title: "Arslan Estates",
    client: "Arslan Estates",
    kind: "Web Design · Real Estate",
    year: "2023",
    role: "Design / Development",
    collaborator: "Saiber",
    tags: ["Real Estate", "Corporate", "SEO", "KKTC"],
    image: "story-01.jpg",
    summary: "Real estate agency website with property listings.",
    body: [
      "Arslan Estates için emlak ilan yönetimi, mülk detay sayfaları ve müşteri iletişimi sunan profesyonel bir gayrimenkul web sitesi geliştirdik. Modern tasarım ve gelişmiş filtreleme sistemi ile alıcı deneyimini iyileştirdik.",
      "SEO optimizasyonu, harita entegrasyonu ve sosyal medya bağlantıları ile dijital görünürlüğü artırdık. Çok dilli yapı ile uluslararası müşterilere ulaşmayı sağladık.",
    ],
    scope: "Web design, real estate, SEO",
    previews: {
      desktop: '/assets/previews/desktop/arslan-estates.webp',
    },
  },
  {
    n: "18",
    slug: "arslan-coin-center",
    title: "Arslan Coin Center",
    client: "Arslan Coin Center",
    kind: "Web Design · Finance",
    year: "2024",
    role: "Design / Development",
    collaborator: "Saiber",
    tags: ["Finance", "Crypto", "Exchange", "KKTC"],
    image: "story-02.jpg",
    summary: "Cryptocurrency exchange and trading center website.",
    body: [
      "Arslan Coin Center için kripto para alım-satım ve takas hizmetlerini sunan modern bir web sitesi geliştirdik. Güvenilirlik ve şeffaflık vurgulayan profesyonel bir tasarım uyguladık.",
      "Hizmet bilgileri, konum detayları ve iletişim araçları ile müşteri edinimini kolaylaştırdık. SEO ve sosyal medya entegrasyonu ile dijital varlığı güçlendirdik.",
    ],
    scope: "Web design, finance, crypto",
    previews: {
      desktop: '/assets/previews/desktop/arslan-coin-center.webp',
    },
  },
  {
    n: "19",
    slug: "arslan-group",
    title: "Arslan Group",
    client: "Arslan Group",
    kind: "Web Design · Corporate",
    year: "2021",
    role: "Design / Development",
    collaborator: "Saiber",
    tags: ["Corporate", "Holding", "Multi-language", "KKTC"],
    image: "story-03.jpg",
    summary: "Multi-company holding group corporate website.",
    body: [
      "Arslan Group için emlak, finans ve ticaret alanlarındaki şirketlerini tek çatı altında sunan kurumsal bir holding web sitesi geliştirdik. Grup yapısını, iş kollarını ve kurumsal vizyonu profesyonel şekilde sergileyen kapsamlı bir platform oluşturduk.",
      "Modern tasarım, çok dilli yapı ve SEO optimizasyonu ile güçlü bir kurumsal dijital kimlik oluşturduk.",
    ],
    scope: "Web design, corporate, holding",
    previews: {
      desktop: '/assets/previews/desktop/arslan-group.webp',
    },
  },
  {
    n: "20",
    slug: "homes-in-mediterranean",
    title: "Homes in Mediterranean",
    client: "Homes in Mediterranean",
    kind: "Web Design · Real Estate",
    year: "2024",
    role: "Design / Development",
    collaborator: "Saiber",
    tags: ["Real Estate", "International", "Platform", "SEO"],
    image: "story-04.jpg",
    summary: "International Mediterranean real estate platform.",
    body: [
      "Homes in Mediterranean için Akdeniz bölgesindeki gayrimenkul fırsatlarını uluslararası yatırımcılara sunan kapsamlı bir emlak platformu geliştirdik. Mülk detayları, bölge rehberleri ve yatırım bilgileri ile zengin bir içerik yapısı oluşturduk.",
      "Çok dilli yapı, gelişmiş arama ve filtreleme özellikleri, SEO optimizasyonu ile global müşteri kitlesine ulaşmayı hedefledik.",
    ],
    scope: "Web design, real estate, international",
    previews: {
      desktop: '/assets/previews/desktop/homes-in-mediterranean.webp',
      mobile: '/assets/previews/mobile/homes-in-mediterranean.webp',
    },
  },
  {
    n: "21",
    slug: "sosyal-piton",
    title: "Sosyal Piton",
    client: "Sosyal Piton",
    kind: "Web Design · Agency",
    year: "2024",
    role: "Design / Development",
    tags: ["Agency", "Social Media", "Portfolio", "Creative"],
    image: "story-05.jpg",
    summary: "Social media management agency portfolio website.",
    body: [
      "Sosyal Piton için sosyal medya yönetimi ve dijital pazarlama hizmetlerini sergileyen yaratıcı bir ajans web sitesi geliştirdik. Portfolyo, hizmet detayları ve müşteri referansları ile güçlü bir marka imajı oluşturduk.",
      "Dinamik tasarım, animasyonlar ve görsel odaklı içerik ile ajansın yaratıcı kimliğini dijitale taşıdık. SEO ve performans optimizasyonu ile organik erişimi artırdık.",
    ],
    scope: "Web design, agency, portfolio",
  },
  {
    n: "22",
    slug: "kibris-lefkosa-taksi",
    title: "Kıbrıs Lefkoşa Taksi",
    client: "Kıbrıs Lefkoşa Taksi",
    kind: "Web Design · Transportation",
    year: "2023",
    role: "Design / Development / SEO",
    tags: ["Transportation", "Booking", "SEO", "KKTC"],
    image: "story-01.jpg",
    summary: "Taxi booking and transportation service website in Nicosia.",
    body: [
      "Kıbrıs Lefkoşa Taksi için online taksi çağırma, rota hesaplama ve fiyat bilgisi sunan profesyonel bir web sitesi geliştirdik. WhatsApp ve telefon entegrasyonu ile hızlı iletişim sağladık.",
      "Yerel SEO optimizasyonu ile 'lefkoşa taksi', 'kıbrıs taksi' gibi aramalarda üst sıralarda yer almayı başardık. Mobil öncelikli tasarım ile hareket halindeki kullanıcılara kolay erişim sunduk.",
    ],
    scope: "Web design, transportation, SEO",
    previews: {
      desktop: '/assets/previews/desktop/kibris-lefkosa-taksi.webp',
      mobile: '/assets/previews/mobile/kibris-lefkosa-taksi.webp',
    },
  },
  {
    n: "23",
    slug: "aydin-transfer",
    title: "Aydın Transfer",
    client: "Aydın Transfer",
    kind: "Web Design · Transportation",
    year: "2024",
    role: "Design / Development / SEO",
    tags: ["Transportation", "Transfer", "Booking", "KKTC"],
    image: "story-02.jpg",
    summary: "Airport transfer and VIP transportation service website.",
    body: [
      "Aydın Transfer için havalimanı transfer ve şehirlerarası ulaşım hizmetlerini sunan profesyonel bir web sitesi geliştirdik. Online rezervasyon, rota bilgileri ve fiyat hesaplama ile kullanıcı deneyimini ön plana çıkardık.",
      "Yerel SEO optimizasyonu, WhatsApp entegrasyonu ve mobil öncelikli tasarım ile müşteri edinimini artırdık.",
    ],
    scope: "Web design, transportation, booking",
    previews: {
      desktop: '/assets/previews/desktop/aydin-transfer.webp',
      mobile: '/assets/previews/mobile/aydin-transfer.webp',
    },
  },
  {
    n: "24",
    slug: "kardesler-taxi",
    title: "Kardeşler Taxi",
    client: "Kardeşler Taxi",
    kind: "Web Design · Transportation",
    year: "2025",
    role: "Design / Development / SEO",
    tags: ["Transportation", "Taxi", "Booking", "KKTC"],
    image: "story-03.jpg",
    summary: "Taxi service website with online booking and route info.",
    body: [
      "Kardeşler Taxi için online taksi çağırma, fiyat bilgisi ve rota hesaplama sunan modern bir web sitesi geliştirdik. Hızlı iletişim butonları ve WhatsApp entegrasyonu ile anında ulaşım sağladık.",
      "Yerel SEO çalışmaları ile taksi aramalarında üst sıralarda yer almayı hedefledik. Mobil uyumlu tasarım ile hareket halindeki kullanıcılara kolay erişim sunduk.",
    ],
    scope: "Web design, transportation, SEO",
    previews: {
      desktop: '/assets/previews/desktop/kardesler-taxi.webp',
    },
  },
  {
    n: "25",
    slug: "sammys-hotel",
    title: "Sammys Hotel",
    client: "Sammys Hotel",
    kind: "Web Design · Hospitality",
    year: "2023",
    role: "Design / Development",
    collaborator: "Saiber",
    tags: ["Hotel", "Hospitality", "Booking", "KKTC"],
    image: "story-04.jpg",
    summary: "Boutique hotel website with room booking and gallery.",
    body: [
      "Sammys Hotel için oda rezervasyonu, fotoğraf galerisi ve otel bilgilerini sergileyen şık bir web sitesi tasarladık. Misafir deneyimini ön plana çıkaran sıcak ve davetkar bir tasarım anlayışı uyguladık.",
      "Online rezervasyon entegrasyonu, çok dilli yapı ve SEO optimizasyonu ile uluslararası turistlere ulaşmayı sağladık.",
    ],
    scope: "Web design, hospitality, booking",
    previews: {
      desktop: '/assets/previews/desktop/sammys-hotel.webp',
      mobile: '/assets/previews/mobile/sammys-hotel.webp',
    },
  },
  {
    n: "26",
    slug: "all-pro-cyprus",
    title: "All Pro Cyprus",
    client: "All Pro Cyprus",
    kind: "Web Design · Services",
    year: "2022",
    role: "Design / Development",
    collaborator: "Saiber",
    tags: ["Services", "Corporate", "Multi-language", "KKTC"],
    image: "story-05.jpg",
    summary: "Multi-service company website in North Cyprus.",
    body: [
      "All Pro Cyprus için çoklu hizmet alanlarını kapsayan profesyonel bir kurumsal web sitesi geliştirdik. Hizmet detayları, referanslar ve iletişim bilgileri ile güçlü bir dijital varlık oluşturduk.",
      "Modern tasarım, SEO optimizasyonu ve mobil uyumlu yapı ile müşteri edinimini kolaylaştırdık. Çok dilli yapı ile yerli ve yabancı müşterilere ulaşmayı sağladık.",
    ],
    scope: "Web design, services, corporate",
    previews: {
      desktop: '/assets/previews/desktop/all-pro-cyprus.webp',
      mobile: '/assets/previews/mobile/all-pro-cyprus.webp',
    },
  },
  {
    n: "27",
    slug: "alert-muhendislik",
    title: "Alert Mühendislik",
    client: "Alert Mühendislik",
    kind: "Web Design · Corporate",
    year: "2022",
    role: "Design / Development",
    collaborator: "Saiber",
    tags: ["Corporate", "Engineering", "Responsive", "SEO"],
    image: "story-01.jpg",
    summary: "Engineering and construction company corporate website.",
    body: [
      "Alert Mühendislik için mühendislik ve inşaat hizmetlerini sergileyen kurumsal bir web sitesi tasarladık. Proje portföyü, hizmet detayları ve iletişim bilgileri ile güçlü bir dijital kimlik oluşturduk.",
      "Responsive tasarım, hızlı yüklenme süreleri ve SEO optimizasyonu ile potansiyel müşterilerin kolayca ulaşmasını sağladık.",
    ],
    scope: "Web design, corporate, engineering",
    previews: {
      desktop: '/assets/previews/desktop/alert-muhendislik.webp',
      mobile: '/assets/previews/mobile/alert-muhendislik.webp',
    },
  },
  {
    n: "28",
    slug: "beton-store",
    title: "Beton Store",
    client: "Beton Store",
    kind: "Web Design · E-commerce",
    year: "2024",
    role: "Design / Development",
    tags: ["E-commerce", "Construction", "Responsive", "SEO"],
    image: "story-02.jpg",
    summary: "Construction materials online store.",
    body: [
      "Beton Store için yapı malzemeleri ve beton ürünlerinin satışını yapan bir e-ticaret platformu geliştirdik. Ürün kataloğu, sipariş yönetimi ve iletişim sistemi ile kapsamlı bir dijital mağaza oluşturduk.",
      "Modern tasarım ve kullanıcı dostu arayüz ile müşteri deneyimini ön plana çıkardık. SEO optimizasyonu ile organik trafik artışı sağladık.",
    ],
    scope: "Web design, e-commerce, construction",
    previews: {
      desktop: '/assets/previews/desktop/beton-store.webp',
      mobile: '/assets/previews/mobile/beton-store.webp',
    },
  },
  {
    n: "29",
    slug: "virginia-ice-cream",
    title: "Virginia Ice Cream",
    client: "Virginia Ice Cream",
    kind: "Web Design · F&B",
    year: "2023",
    role: "Design / Development",
    collaborator: "Saiber",
    tags: ["F&B", "Brand", "Responsive", "SEO"],
    image: "story-01.jpg",
    summary: "Premium ice cream brand website with menu and locations.",
    body: [
      "Virginia Ice Cream için premium dondurma markasının dijital kimliğini oluşturan şık ve renkli bir web sitesi tasarladık. Menü, lezzet kataloğu ve şube bilgileri ile müşteri deneyimini ön plana çıkardık.",
      "Markanın enerjik ve eğlenceli kişiliğini yansıtan görsel tasarım, animasyonlar ve responsive yapı ile güçlü bir marka dijitale taşıdık.",
    ],
    scope: "Web design, F&B, brand",
    previews: {
      desktop: '/assets/previews/desktop/virginia-ice-cream.webp',
      mobile: '/assets/previews/mobile/virginia-ice-cream.webp',
    },
  },
  {
    n: "30",
    slug: "welcome-pickups",
    title: "Welcome Pickups",
    client: "Welcome Pickups",
    kind: "Web Design · Transportation",
    year: "2024",
    role: "Design / Development",
    tags: ["Transportation", "Transfer", "Booking", "International"],
    image: "story-03.jpg",
    summary: "Airport transfer and welcome service website.",
    body: [
      "Welcome Pickups için havalimanı karşılama ve transfer hizmetlerini sunan profesyonel bir web sitesi geliştirdik. Online rezervasyon, rota bilgileri ve müşteri yorumları ile kapsamlı bir platform oluşturduk.",
      "Uluslararası müşterilere yönelik çok dilli yapı, hızlı yüklenme ve mobil uyumlu tasarım ile güçlü bir dijital varlık oluşturduk.",
    ],
    scope: "Web design, transportation, booking",
    previews: {
      mobile: '/assets/previews/mobile/welcome-pickups.webp',
    },
  },
  {
    n: "31",
    slug: "mindloop",
    title: "Mindloop",
    client: "Mindloop",
    kind: "Web Design · Personal",
    year: "2026",
    role: "Design / Development",
    tags: ["3D", "Personal Brand", "Interactive", "Newsletter"],
    image: "story-02.jpg",
    summary: "Personal 3D interactive website with immersive scroll-driven storytelling.",
    body: [
      "Mindloop, kişisel markamı 3D ve interaktif bir deneyimle sergilediğim bireysel bir proje. Koyu temalı, atmosferik bir 3D sahne üzerine kurulu hero bölümü ve scroll ile derinleşen bir anlatım kurguladım.",
      "Newsletter aboneliği, sosyal medya entegrasyonu ve Home / How It Works / Philosophy / Use Cases sayfalarıyla teknoloji ve derinlik temalı bir içerik akışı sunuyor.",
    ],
    scope: "Web design, 3D, personal brand",
    url: "https://mindloop-landing-page-phi.vercel.app/",
    previews: {
      desktop: '/assets/previews/desktop/mindloop.webp',
      mobile: '/assets/previews/mobile/mindloop.webp',
    },
  },
  {
    n: "32",
    slug: "dental-health",
    title: "Dental Health",
    client: "Dental Health",
    kind: "Web Design · Healthcare",
    year: "2026",
    role: "Design / Development",
    tags: ["Healthcare", "Dental", "Corporate", "Responsive"],
    image: "story-03.jpg",
    summary: "Dental clinic website with service highlights and appointment booking.",
    body: [
      "Dental Health için West New York merkezli diş kliniğinin hizmetlerini sergileyen temiz ve güven veren bir web sitesi tasarladık. Gelişmiş diş tedavileri, kaliteli ekipman ve uzman kadro vurgusu ile hasta güveni oluşturan bir dijital kimlik oluşturduk.",
      "Ücretsiz konsültasyon çağrısı, acil durum iletişim bilgileri ve responsive tasarım ile hasta edinimini kolaylaştırdık.",
    ],
    scope: "Web design, healthcare, corporate",
    previews: {
      desktop: '/assets/previews/desktop/dental-health.webp',
      mobile: '/assets/previews/mobile/dental-health.webp',
    },
  },
  {
    n: "33",
    slug: "securify",
    title: "Securify",
    client: "Securify",
    kind: "Web Design · SaaS",
    year: "2026",
    role: "Design / Development",
    tags: ["SaaS", "Security", "Dark Theme", "Landing Page"],
    image: "story-05.jpg",
    summary: "Data security SaaS landing page with bold typography and stats.",
    body: [
      "Securify için veri güvenliği ve gizlilik odaklı bir SaaS platformunun landing page'ini tasarladık. Koyu temalı, büyük tipografi ve etkileyici istatistiklerle (1.5B+ korunan veri, 65K+ girişim kullanıcısı) güven veren bir marka anlatımı kurguladık.",
      "Platform, çözümler, şirket ve destek sayfalarını kapsayan modern bir navigasyon yapısı ile SaaS ürününü net şekilde konumlandırdık.",
    ],
    scope: "Web design, SaaS, branding",
    previews: {
      desktop: '/assets/previews/desktop/securify.webp',
      mobile: '/assets/previews/mobile/securify.webp',
    },
  },
  {
    n: "34",
    slug: "odeme-takip-botu",
    title: "Ödeme Takip Botu",
    client: "Piton Studios",
    kind: "Automation · Backend",
    year: "2025",
    role: "Development",
    tags: ["Node.js", "Telegram Bot", "Automation", "Fintech"],
    image: "story-01.jpg",
    summary: "Payment-tracking web app with automatic Telegram due-date reminders.",
    body: [
      "Şirket ödemelerini (kredi kartı/taksitli, çek, elden ve diğer) takip eden; vade tarihi yaklaşınca Telegram üzerinden otomatik hatırlatma gönderen bir web uygulaması geliştirdik. Node.js, Express ve SQLite üzerine kurulu hafif ama güvenilir bir altyapı kullandık.",
      "Taksitli ödemelerde otomatik vade üretimi, geciken ve önümüzdeki 7 gün için özet panel, ödenmiş kayıtlar için finansal bütünlük koruması gibi özelliklerle iş süreçlerini otomatikleştirmenin somut bir örneğini ortaya koyduk.",
    ],
    scope: "Automation, backend, Telegram integration",
  },
  {
    n: "35",
    slug: "deprem-erken-uyari",
    title: "Deprem Erken Uyarı",
    client: "Piton Studios",
    kind: "AI / ML · Deep Learning",
    year: "2025",
    role: "Research / Development",
    tags: ["Python", "1D CNN", "Time Series", "Early Warning"],
    image: "story-02.jpg",
    summary: "Earthquake early-warning simulation detecting P-waves from seismic data with a 1D CNN.",
    body: [
      "Sismik zaman serisi verisinden P-dalgalarını tespit ederek deprem erken uyarı senaryosunu simüle eden bir derin öğrenme projesi geliştirdik. Python ile kurulan 1D CNN mimarisi, ham sinyalden hızlı ve doğru dalga tespiti yapıyor.",
      "Bir Ar-Ge projesi olarak; veri hazırlama, model eğitimi ve değerlendirme adımlarının tamamını kapsıyor. Zaman serisi derin öğrenme yetkinliğimizin somut bir kanıtı.",
    ],
    scope: "Deep learning, time series, research",
  },
  {
    n: "36",
    slug: "arac-takip-yolo",
    title: "Araç Takip Sistemi",
    client: "Piton Studios",
    kind: "AI / ML · Computer Vision",
    year: "2025",
    role: "Research / Development",
    tags: ["YOLOv11", "ByteTrack", "Object Tracking", "Python"],
    image: "story-03.jpg",
    summary: "Multi-vehicle detection and tracking in video with YOLO11 and ByteTrack, fine-tuned on custom data.",
    body: [
      "Video akışında birden fazla aracı gerçek zamanlı tespit edip takip eden bir bilgisayarlı görü sistemi geliştirdik. Ultralytics YOLO11 modelini kendi veri setimizle fine-tune ederek, ByteTrack ile kimlik korumalı takip sağladık.",
      "Trafik analizi, güvenlik ve akıllı şehir senaryolarına uyarlanabilir bu Ar-Ge projesi; nesne tespiti, takip ve model iyileştirme yetkinliklerimizi bir arada sergiliyor.",
    ],
    scope: "Computer vision, object tracking, research",
    previews: {
      desktop: '/assets/previews/desktop/arac-takip-yolo.webp',
    },
  },
  {
    n: "37",
    slug: "trafik-levha-okuma",
    title: "Trafik Levha Okuma",
    client: "Piton Studios",
    kind: "AI / ML · Computer Vision",
    year: "2025",
    role: "Research / Development",
    tags: ["YOLO", "CNN", "Classification", "Python"],
    image: "story-04.jpg",
    summary: "Two-stage pipeline: YOLO detects traffic signs, a CNN classifies them.",
    body: [
      "Görüntüdeki trafik levhalarını önce YOLO ile tespit eden, ardından kırpılan bölgeleri CNN ile sınıflandıran iki aşamalı bir bilgisayarlı görü pipeline'ı geliştirdik.",
      "Sürücü destek sistemleri ve harita güncelleme senaryolarına temel olabilecek bu Ar-Ge çalışması; tespit ve sınıflandırma modellerini tek üretim hattında birleştirme deneyimimizi gösteriyor.",
    ],
    scope: "Computer vision, classification pipeline, research",
  },
  {
    n: "38",
    slug: "yuz-duygu-analizi",
    title: "Yüz Duygu Analizi",
    client: "Piton Studios",
    kind: "AI / ML · Computer Vision",
    year: "2025",
    role: "Research / Development",
    tags: ["MediaPipe", "Face Mesh", "Real-time", "Python"],
    image: "story-05.jpg",
    summary: "Real-time, explainable emotion estimation from 468 MediaPipe Face Mesh landmarks.",
    body: [
      "MediaPipe Face Mesh'in çıkardığı 468 yüz noktasını kullanarak gerçek zamanlı duygu tahmini yapan bir sistem geliştirdik. Kara kutu yerine kural tabanlı ve açıklanabilir bir yaklaşım tercih ettik — her tahminin gerekçesi izlenebilir.",
      "Web kamerasıyla anlık çalışan bu Ar-Ge projesi; kullanıcı deneyimi araştırmaları ve etkileşimli uygulamalar için temel oluşturabilecek pratik bir bilgisayarlı görü örneği.",
    ],
    scope: "Computer vision, real-time analysis, research",
  },
  {
    n: "39",
    slug: "hava-goruntu-segmentasyonu",
    title: "Hava Görüntüsü Segmentasyonu",
    client: "Piton Studios",
    kind: "AI / ML · Computer Vision",
    year: "2025",
    role: "Research / Development",
    tags: ["U-Net", "Segmentation", "Satellite", "Python"],
    image: "story-01.jpg",
    summary: "Six-class semantic segmentation of satellite imagery with U-Net.",
    body: [
      "Uydu görüntülerini bina, yol, bitki örtüsü gibi 6 sınıfa ayıran bir semantik segmentasyon modeli geliştirdik. U-Net mimarisi ile piksel bazında yüksek doğruluklu ayrım sağladık.",
      "Üretime yakın bir yapıda kurgulanan bu Ar-Ge projesi; şehir planlama, tarım ve afet analizi gibi alanlarda kullanılabilecek coğrafi veri işleme yetkinliğimizi gösteriyor.",
    ],
    scope: "Semantic segmentation, satellite imagery, research",
  },
  {
    n: "40",
    slug: "fuze-gudum-simulasyonu",
    title: "Füze Güdüm Görselleştirme",
    client: "Piton Studios",
    kind: "Simulation · Visualization",
    year: "2024",
    role: "Research / Development",
    tags: ["Python", "Simulation", "Guidance", "Visualization"],
    image: "story-02.jpg",
    summary: "Python visualization of missile guidance algorithms.",
    body: [
      "Güdüm algoritmalarının davranışını simüle eden ve adım adım görselleştiren bir Python projesi geliştirdik. Takip geometrisi ve yörünge hesaplamaları etkileşimli grafiklerle izlenebiliyor.",
      "Matematiksel modelleme ile görselleştirmeyi birleştiren bu Ar-Ge çalışması; karmaşık algoritmaları anlaşılır çıktılara dönüştürme yetkinliğimizin bir örneği.",
    ],
    scope: "Simulation, algorithm visualization, research",
    previews: {
      desktop: '/assets/previews/desktop/fuze-gudum-simulasyonu.webp',
    },
  },
  {
    n: "41",
    slug: "contentflow-ai",
    title: "ContentFlow AI",
    client: "ContentFlow AI",
    kind: "SaaS · AI",
    year: "2025",
    role: "Product / Development",
    tags: ["Next.js", "AI", "Content", "SaaS"],
    image: "story-03.jpg",
    summary: "AI-assisted content generation and workflow SaaS prototype built with Next.js.",
    body: [
      "ContentFlow AI, içerik üretim sürecini yapay zekâ ile hızlandıran bir SaaS ürün prototipi. Next.js üzerinde kurulan yapı; içerik fikrinden taslağa ve yayın akışına uzanan adımları tek panelde topluyor.",
      "Kendi ürün fikrimiz olarak geliştirdiğimiz bu prototip; AI entegrasyonu, SaaS mimarisi ve ürünleştirme deneyimimizi bir arada gösteriyor.",
    ],
    scope: "SaaS product, AI content, prototype",
  },
  {
    n: "42",
    slug: "social-pro",
    title: "Social Pro",
    client: "Social Pro",
    kind: "SaaS · Social Media",
    year: "2025",
    role: "Product / Development",
    tags: ["Next.js", "Social Media", "SaaS", "Dashboard"],
    image: "story-04.jpg",
    summary: "Social media management SaaS prototype with scheduling and a unified dashboard.",
    body: [
      "Social Pro, birden fazla sosyal medya hesabını tek panelden yönetmeyi hedefleyen bir SaaS prototipi. İçerik planlama, takvim ve performans görünümleri Next.js üzerinde kurgulandı.",
      "Kendi ürün fikrimiz olan bu çalışma; dashboard tasarımı, çoklu hesap mimarisi ve SaaS ürünleştirme adımlarındaki deneyimimizi yansıtıyor.",
    ],
    scope: "SaaS product, social media management, prototype",
  },
  {
    n: "43",
    slug: "holly-trader",
    title: "Holly Trader",
    client: "Holly Trader",
    kind: "Web App · Fintech",
    year: "2025",
    role: "Product / Development",
    tags: ["Node.js", "Trading", "Analytics", "Automation"],
    image: "story-05.jpg",
    summary: "Trading and analysis tool prototype built on Node.js.",
    body: [
      "Holly Trader, piyasa verilerini izleyip alım-satım analizleri sunan Node.js tabanlı bir araç prototipi. Veri toplama, sinyal üretimi ve raporlama akışları tek serviste birleşiyor.",
      "Fintech alanındaki bu ürün denememiz; gerçek zamanlı veri işleme ve otomasyon yetkinliğimizi gösteren bir yan proje.",
    ],
    scope: "Fintech tool, analytics, prototype",
  },
  {
    n: "44",
    slug: "lithos",
    title: "Lithos",
    client: "Lithos",
    kind: "Web Design · Interactive",
    year: "2026",
    role: "Design / Development",
    tags: ["Interactive", "Education", "Landing Page", "Geology"],
    image: "story-02.jpg",
    summary: "Interactive geology education concept — peel back the layers of the earth with cursor-driven exploration.",
    body: [
      "Lithos, jeolojiyi interaktif bir deneyimle anlatan bir eğitim platformu konsepti. 'Layers hold tales of time' teması etrafında; imleç hareketiyle yer kabuğunun katmanlarını keşfettiren etkileşimli bir hero deneyimi kurguladık.",
      "Kurs, saha rehberleri ve canlı tur bölümleriyle kurgulanan bu kendini geliştirme projesi; interaktif storytelling ve deneysel arayüz tasarımı yetkinliğimizi gösteriyor.",
    ],
    scope: "Interactive landing, education concept",
    url: "https://lithos-interactive-geology.vercel.app/",
    previews: {
      desktop: '/assets/previews/desktop/lithos.webp',
      mobile: '/assets/previews/mobile/lithos.webp',
    },
  },
  {
    n: "45",
    slug: "vanguard",
    title: "Vanguard",
    client: "Vanguard",
    kind: "Web Design · Landing Page",
    year: "2026",
    role: "Design / Development",
    tags: ["Landing Page", "Agency", "Typography", "Animation"],
    image: "story-03.jpg",
    summary: "Bold creative-agency landing concept — 'Design. Disrupt. Conquer.'",
    body: [
      "Vanguard, kreatif ajans kimliği için tasarladığımız cesur bir landing page konsepti. 'Design. Disrupt. Conquer.' sloganı etrafında büyük tipografi, güçlü kontrast ve etkileyici istatistik blokları (250+ marka, %95 müşteri sadakati) kullandık.",
      "Kendini geliştirme amaçlı bu çalışma; marka dili kurma, tipografik hiyerarşi ve yüksek etkili landing tasarımı becerilerimizi sergiliyor.",
    ],
    scope: "Landing page, brand concept",
    url: "https://vanguard-landing-page-six.vercel.app/",
    previews: {
      desktop: '/assets/previews/desktop/vanguard.webp',
      mobile: '/assets/previews/mobile/vanguard.webp',
    },
  },
  {
    n: "46",
    slug: "jack-portfolio",
    title: "Jack — 3D Creator",
    client: "Jack Portfolio",
    kind: "Web Design · Portfolio",
    year: "2026",
    role: "Design / Development",
    tags: ["3D", "Portfolio", "Animation", "Personal Brand"],
    image: "story-04.jpg",
    summary: "3D creator portfolio concept with scroll-driven text animations and immersive visuals.",
    body: [
      "Jack, bir 3D içerik üreticisi için tasarladığımız portfolyo sitesi konsepti. Scroll ile harf harf açılan metin animasyonları, projeler galerisi ve fiyatlar bölümüyle kişisel marka anlatısı kurduk.",
      "Kendini geliştirme amaçlı bu çalışma; animasyon koreografisi ve kişisel marka portfolyosu tasarımındaki yaklaşımımızı gösteriyor.",
    ],
    scope: "Portfolio concept, 3D, animation",
    url: "https://3d-jack-portfolio.vercel.app/",
    previews: {
      desktop: '/assets/previews/desktop/jack-portfolio.webp',
      mobile: '/assets/previews/mobile/jack-portfolio.webp',
    },
  },
  {
    n: "47",
    slug: "veldara",
    title: "Veldara",
    client: "Veldara",
    kind: "Web Design · Developer Tool",
    year: "2026",
    role: "Design / Development",
    tags: ["Three.js", "Svelte", "Landing Page", "Developer Tool"],
    image: "story-05.jpg",
    summary: "Landing concept for a Svelte 5 + Three.js library — documentation, showcase and modules.",
    body: [
      "Veldara, Svelte 5 ile Three.js'i birleştiren bir geliştirici kütüphanesi konsepti için tasarladığımız landing page. Dokümantasyon, showcase ve modüller bölümleriyle developer-first bir ürün anlatımı kurduk.",
      "3D web deneyimlerine odaklanan bu kendini geliştirme projesi; teknik ürün pazarlaması ve developer-tool arayüz tasarımı yetkinliğimizi gösteriyor.",
    ],
    scope: "Developer-tool landing, 3D",
    url: "https://veldara-landing-page-sigma.vercel.app/",
    previews: {
      desktop: '/assets/previews/desktop/veldara.webp',
      mobile: '/assets/previews/mobile/veldara.webp',
    },
  },
  {
    n: "48",
    slug: "emlak-sync",
    title: "Emlak Sync",
    client: "Emlak Sync",
    kind: "Web App · Automation",
    year: "2026",
    role: "Product / Development",
    tags: ["Automation", "Real Estate", "Integration", "SaaS"],
    image: "story-04.jpg",
    summary: "Multi-portal real estate listing sync panel — enter once, publish everywhere.",
    body: [
      "Emlak Sync, emlak ofisleri için geliştirdiğimiz çoklu-platform ilan senkronizasyon paneli. İlan tek yerden girilir; KKTC emlak portallarına (HangiEv, 101evler) otomatik yayınlanır ve senkron tutulur.",
      "Mükerrer veri girişini ortadan kaldıran bu kendi ürünümüz; portal entegrasyonları, veri senkronizasyonu ve emlak sektörüne özel otomasyon yetkinliğimizi gösteriyor.",
    ],
    scope: "Listing sync, portal integrations, automation",
  },
  {
    n: "49",
    slug: "dolmus-kontrol",
    title: "Dolmuş Güzergah Kontrol",
    client: "Piton Studios",
    kind: "Automation · Data",
    year: "2026",
    role: "Development",
    tags: ["Python", "Flask", "Automation", "Reporting"],
    image: "story-01.jpg",
    summary: "Route-compliance automation: GPS tracker Excel data becomes minibus route control reports.",
    body: [
      "Şehirdeki dolmuş hatlarının zamanında çalışıp çalışmadığını denetleyen bir otomasyon sistemi geliştirdik. GPS takip programından alınan Excel verisi işlenerek hat bazında güzergah kontrol raporları üretiliyor.",
      "Flask tabanlı bu web uygulaması; elle yapılan saatlerce süren kontrolü dakikalara indiriyor — veri işleme ve süreç otomasyonu yetkinliğimizin sahadan bir örneği.",
    ],
    scope: "Automation, data processing, reporting",
  },
];

export const SERVICES: Service[] = [
  {
    n: "01",
    slug: "web-design",
    title: "Web Design",
    cat: "Design",
    desc: "Brand-driven marketing sites with considered type, motion, and editorial rhythm.",
    items: ["Landing · Marketing", "Portfolio · Editorial", "Design systems"],
    longDesc:
      "We design marketing sites that move with intention — every typographic choice, spacing decision, and motion detail serves the brand story. The result is a site that feels authored, not assembled. We work from strategy to final pixel, covering information architecture, interaction design, and handoff-ready component systems.",
    features: [
      { title: "Brand-First Layout", desc: "Every layout starts from the brand's visual language, not a template. Grid, type scale, and spacing are derived from the identity." },
      { title: "Editorial Typography", desc: "Type is treated as the primary design element — scale, rhythm, and hierarchy are set before color or imagery." },
      { title: "Motion Design", desc: "Purposeful animation that enhances storytelling without distracting. Entrances, transitions, and micro-interactions are storyboarded." },
      { title: "Design Systems", desc: "Component libraries with documented tokens, variants, and usage guidelines — so your team can extend the design without breaking it." },
      { title: "Responsive First", desc: "Every breakpoint is designed, not just resized. Mobile is a first-class experience, not an afterthought." },
      { title: "CMS Integration", desc: "Contentful, Sanity, or headless setups that let non-technical editors publish at pace without touching code." },
    ],
    process: [
      { step: "01", title: "Discovery", desc: "Brand audit, competitor analysis, stakeholder interviews. We establish what the site needs to say and who it needs to say it to." },
      { step: "02", title: "Architecture", desc: "Sitemap, content model, and page wireframes. Structure before style." },
      { step: "03", title: "Visual Direction", desc: "Two visual directions explored, one developed. Type, color, and layout language defined." },
      { step: "04", title: "Design Build", desc: "Full-fidelity Figma components across all breakpoints, with interaction specs and motion notes." },
      { step: "05", title: "Handoff", desc: "Developer-ready files, design tokens exported, component annotations, and a recorded walkthrough." },
    ],
    stats: [
      { value: "3–6 wks", label: "Typical timeline" },
      { value: "30+", label: "Sites delivered" },
      { value: "90+", label: "Lighthouse target" },
      { value: "Next.js / WordPress", label: "Stack used" },
    ],
    faq: [
      { q: "Do you build the site or just design it?", a: "Both. We offer design-only engagements for teams with developers, and full design-to-code delivery. Most clients take the full package." },
      { q: "What if we already have a brand?", a: "We work with existing brand systems and extend them into digital. We'll audit what you have and adapt rather than override." },
      { q: "How many revision rounds are included?", a: "Two rounds per major phase. Additional rounds are billed at our hourly rate. In practice, we rarely hit that limit because we align early." },
      { q: "Can you work with our existing CMS?", a: "Yes — we've built on Webflow, Framer, WordPress, Contentful, Sanity, and custom Next.js setups. We'll recommend what fits your team's workflow." },
    ],
    tools: ["Figma", "Framer", "Next.js", "React", "Tailwind", "JavaScript", "TypeScript", "Contentful", "Sanity", "Vercel"],
    relatedServices: ["web-app", "ai-integration", "seo-geo"],
  },
  {
    n: "02",
    slug: "web-app",
    title: "Web App",
    cat: "Build",
    desc: "Full-stack product surfaces — dashboards, tools, internal systems that hold up at scale.",
    items: ["React / Next.js", "Auth · Billing · Roles", "Realtime · API design"],
    longDesc:
      "We build product-grade web applications that handle real load, real users, and real complexity. From the data model to the dashboard UI, every layer is considered. We specialize in Next.js full-stack builds with authentication, billing, role-based access, and real-time features — shipped with observability from day one.",
    features: [
      { title: "Full-Stack Architecture", desc: "Next.js App Router with server components, API routes, and edge functions. TypeScript throughout, no compromises." },
      { title: "Auth & Roles", desc: "Multi-tenant auth with role-based access control. SSO, social login, magic links — whatever your user base needs." },
      { title: "Billing Integration", desc: "Stripe subscriptions, usage-based billing, metered features, and customer portal — wired in from the start, not bolted on later." },
      { title: "Realtime Features", desc: "WebSockets, server-sent events, and optimistic UI for collaborative or live-updating interfaces." },
      { title: "API Design", desc: "RESTful or tRPC APIs with typed contracts, rate limiting, and versioning strategy built in." },
      { title: "Observability", desc: "Error tracking, performance monitoring, and structured logging from day one. You'll know what's breaking before users do." },
    ],
    process: [
      { step: "01", title: "Scoping", desc: "Requirements workshop, technical spec, and architecture decision records. Nothing ambiguous going into build." },
      { step: "02", title: "Data Model", desc: "Schema design, relationships, and indexing strategy before a line of application code is written." },
      { step: "03", title: "Core Build", desc: "Auth, routing, and data layer first. UI components follow once the foundation is solid." },
      { step: "04", title: "Feature Sprints", desc: "Two-week sprints with deployed previews after every sprint. Feedback integrated before moving forward." },
      { step: "05", title: "Launch", desc: "Production environment setup, monitoring configured, documentation written, and team handover session." },
    ],
    stats: [
      { value: "8–16 wks", label: "Typical timeline" },
      { value: "8+", label: "Apps delivered" },
      { value: "99.9%", label: "Uptime target" },
      { value: "<200 ms", label: "API response target" },
    ],
    faq: [
      { q: "Do you work with an existing codebase?", a: "Yes. We've joined projects mid-way, refactored legacy codebases, and extended existing products. We always start with an audit." },
      { q: "What database do you use?", a: "Postgres for most projects, with Prisma or Drizzle as the ORM. We'll use what's already in your stack if you have one." },
      { q: "Do you handle DevOps?", a: "We set up the infrastructure as part of the build — CI/CD, preview environments, and production on Vercel or Google Cloud. Long-term DevOps is a separate engagement." },
      { q: "How do you handle security?", a: "OWASP top-10 is baseline. We also do input validation, CSRF protection, rate limiting, and dependency audits as part of standard delivery." },
    ],
    tools: ["Next.js", "React", "TypeScript", "JavaScript", "PostgreSQL", "Prisma", "Supabase", "Stripe", "Clerk", "Redis", "Python", "Flask", "Vercel", "Google Cloud"],
    relatedServices: ["web-design", "progressive-web-app", "cloud-ecosystem"],
  },
  {
    n: "03",
    slug: "progressive-web-app",
    title: "Progressive Web App",
    cat: "Build",
    desc: "App-like experiences that run in the browser — installable, offline-capable, and no app store required.",
    items: ["PWA · Service Workers", "Offline · Push", "Installable · Fast"],
    longDesc:
      "We build Progressive Web Apps that blur the line between website and native app. Installable on any device, working offline, sending push notifications — all without the friction of app store submission. PWAs load instantly, work on any platform, and cost a fraction of native development while delivering 90% of the same experience.",
    features: [
      { title: "Installable", desc: "Add to Home Screen with a native-looking app icon. Your users launch it like a real app — no browser chrome, full-screen experience." },
      { title: "Offline First", desc: "Service Workers cache critical assets and data. Your app works without a connection and syncs cleanly when it reconnects." },
      { title: "Push Notifications", desc: "Web Push API for re-engagement — segmented, scheduled, and deep-linked, just like native push." },
      { title: "Instant Loading", desc: "Pre-cached shell architecture with streaming SSR. First paint under 1 second, even on slow connections." },
      { title: "Cross-Platform", desc: "One codebase runs everywhere — iOS Safari, Android Chrome, desktop — with platform-appropriate behavior on each." },
      { title: "Auto Updates", desc: "No app store review cycles. Deploy and your users get the latest version on next visit — silently, instantly." },
    ],
    process: [
      { step: "01", title: "Audit & Strategy", desc: "Evaluate which native features you actually need vs. what the web platform already provides. Most teams are surprised." },
      { step: "02", title: "App Shell Design", desc: "Design the installable shell — splash screen, navigation, offline UI states. Feels native from first launch." },
      { step: "03", title: "Core Build", desc: "Next.js + Service Worker setup. Caching strategies, background sync, and push notification infrastructure." },
      { step: "04", title: "Testing", desc: "Lighthouse audit (100/100 PWA score target), cross-browser testing, offline scenario validation on real devices." },
      { step: "05", title: "Launch", desc: "Web App Manifest configured, HTTPS enforced, analytics tracking installed. Your PWA is live everywhere instantly." },
    ],
    stats: [
      { value: "4–10 wks", label: "Typical timeline" },
      { value: "Installable", label: "Core capability" },
      { value: "90+", label: "Lighthouse PWA target" },
      { value: "Single codebase", label: "Delivery model" },
    ],
    faq: [
      { q: "PWA vs native app — when to choose which?", a: "PWA covers 90% of use cases — content apps, dashboards, e-commerce, tools. Go native only if you need hardware APIs like Bluetooth, NFC, or advanced camera controls." },
      { q: "Do PWAs work on iPhone?", a: "Yes. iOS Safari supports installable PWAs, Service Workers, and offline caching. Push notifications arrived in iOS 16.4. The gap with Android is now minimal." },
      { q: "Can users install it from the browser?", a: "Yes — both Chrome and Safari prompt users to 'Add to Home Screen'. The app appears alongside native apps with its own icon." },
      { q: "What about SEO?", a: "PWAs are just websites — fully indexable by Google. You get the SEO benefits of a website plus the engagement of an app." },
    ],
    tools: ["Next.js", "React", "TypeScript", "JavaScript", "Service Workers", "Workbox", "Supabase", "Clerk", "Vercel", "Sentry"],
    relatedServices: ["web-app", "web-design", "automation"],
  },
  {
    n: "04",
    slug: "automation",
    title: "Automation",
    cat: "Ops",
    desc: "Workflow pipelines that quietly replace the spreadsheets no one wants to open.",
    items: ["n8n · Zapier · Make", "Internal tools", "Webhooks · schedulers"],
    longDesc:
      "We map your manual processes and replace them with reliable, observable automation pipelines. Whether it's n8n self-hosted on your infrastructure, Zapier for low-code simplicity, or custom-built webhook handlers — we match the tool to the job. The goal is to eliminate the work that shouldn't require a human.",
    features: [
      { title: "Process Mapping", desc: "We document the current manual workflow before touching any tooling. Understanding the process is 80% of the job." },
      { title: "n8n Self-Hosted", desc: "Full control over your automations with n8n on your own infrastructure. No per-execution pricing, no vendor lock-in." },
      { title: "Zapier & Make", desc: "Rapid deployment for teams that need automation without infrastructure overhead. Right tool for the right job." },
      { title: "Internal Tools", desc: "Custom admin panels, approval workflows, and data management UIs built on top of your automation layer." },
      { title: "Webhook Architecture", desc: "Event-driven pipelines with retry logic, dead letter queues, and idempotency handling." },
      { title: "Scheduled Jobs", desc: "Cron-based data sync, report generation, and maintenance tasks with monitoring and alerting." },
    ],
    process: [
      { step: "01", title: "Process Audit", desc: "Interview the people doing the manual work. Map every step, decision point, and exception case." },
      { step: "02", title: "Automation Design", desc: "Design the automated workflow with error handling and edge cases documented before implementation." },
      { step: "03", title: "Build & Test", desc: "Implement with staging environment testing. Every automation is tested against real data before production." },
      { step: "04", title: "Monitoring Setup", desc: "Alerts for failures, execution logs, and dashboards so you know when something breaks." },
      { step: "05", title: "Handover", desc: "Documentation, training for your team, and a 30-day support window post-launch." },
    ],
    stats: [
      { value: "2–4 wks", label: "Typical timeline" },
      { value: "n8n / webhooks", label: "Core platform" },
      { value: "99.5%", label: "Execution target" },
      { value: "Ongoing upkeep", label: "Engagement model" },
    ],
    faq: [
      { q: "We already use Zapier — can you improve what we have?", a: "Absolutely. We audit existing Zaps, identify fragile steps, and rebuild or extend them. Often we migrate the most complex ones to n8n." },
      { q: "What if the process changes after you build it?", a: "We document everything so your team can maintain it. For ongoing changes, we offer retainer support." },
      { q: "Can you automate across multiple tools?", a: "Yes — multi-system automations are our specialty. CRM, ERP, Slack, email, databases, and custom APIs all connected." },
      { q: "Is n8n hard to manage?", a: "We handle the infrastructure setup and make it manageable. Most clients find it easier than expected after the initial setup." },
    ],
    tools: ["n8n", "Zapier", "Make", "Node.js", "Python", "PostgreSQL", "Redis", "Docker", "Supabase", "Vercel"],
    relatedServices: ["ai-integration", "data-engineering", "cloud-ecosystem"],
  },
  {
    n: "05",
    slug: "ai-integration",
    title: "AI Integration",
    cat: "AI",
    desc: "LLMs, RAG, and agents wired into real products — evaluated, guard-railed, observable.",
    items: ["Claude · OpenAI · Gemini", "RAG · Vector · Memory", "Agents · Tool-use"],
    longDesc:
      "We integrate large language models into real products responsibly — with evaluation frameworks, guardrails, cost controls, and observability built in. We work with Claude, OpenAI, and Gemini, and we choose models based on your use case, not familiarity. RAG pipelines, agent architectures, and tool-use systems are our specialty.",
    features: [
      { title: "Model Selection", desc: "We evaluate models against your specific use case — latency, cost, quality, and capability all factored in. No defaults." },
      { title: "RAG Pipelines", desc: "Retrieval-augmented generation with vector databases, chunking strategies, and re-ranking. Your data, accurately surfaced." },
      { title: "Agent Architecture", desc: "Multi-step agents with tool-use, memory, and planning. Built to complete complex tasks reliably, not just impressively." },
      { title: "Evaluation Framework", desc: "Custom eval suites that measure what matters for your use case. No vibes-based quality assessment." },
      { title: "Guardrails", desc: "Input/output filtering, content policies, and safety layers that match your risk tolerance and regulatory environment." },
      { title: "Observability", desc: "Trace every LLM call, track costs, monitor latency, and alert on quality regressions. LLMOps from the start." },
    ],
    process: [
      { step: "01", title: "Use Case Scoping", desc: "Define the problem the AI should solve and the metrics that define success. Avoid building before you know what 'good' looks like." },
      { step: "02", title: "Prototype & Eval", desc: "Rapid prototype tested against real data. Evaluation suite built alongside the prototype, not after." },
      { step: "03", title: "Pipeline Build", desc: "Production-grade implementation with error handling, fallbacks, and cost controls." },
      { step: "04", title: "Guardrails & Safety", desc: "Input validation, output filtering, and adversarial testing before any user-facing deployment." },
      { step: "05", title: "Monitor & Iterate", desc: "Post-launch monitoring with regular quality reviews and model updates as the landscape evolves." },
    ],
    stats: [
      { value: "6–12 wks", label: "Typical timeline" },
      { value: "5+", label: "AI projects delivered" },
      { value: "Claude / GPT / Gemini", label: "Models used" },
      { value: "Ongoing", label: "Engagement model" },
    ],
    faq: [
      { q: "Which LLM should we use?", a: "It depends on your use case. We'll run a structured evaluation against your actual data and recommend based on results, not hype." },
      { q: "How do you handle hallucinations?", a: "RAG grounds responses in your data. Eval suites catch regressions. Guardrails catch harmful outputs. No single solution — defense in depth." },
      { q: "What does an AI integration cost to run?", a: "We model inference costs as part of the design. Most integrations we build cost $0.01–$0.10 per user session at scale." },
      { q: "Can you improve an existing AI feature?", a: "Yes. We audit the current implementation, identify the failure modes, and improve the pipeline systematically." },
    ],
    tools: ["Claude", "OpenAI", "Gemini", "LangChain", "Python", "TypeScript", "PostgreSQL", "pgvector", "Supabase", "Vercel", "Next.js"],
    relatedServices: ["web-app", "automation", "data-engineering"],
  },
  {
    n: "06",
    slug: "google-ads",
    title: "Google Ads",
    cat: "Growth",
    desc: "Search, performance-max, and display campaigns built around conversion paths, not vanity metrics.",
    items: ["Search · PMax", "Conversion tracking", "Creative iteration"],
    longDesc:
      "We run Google Ads campaigns that are built around your actual conversion path — not impressions, not clicks, not awareness. Every campaign structure, bidding strategy, and creative decision is tied to a measurable business outcome. We set up conversion tracking properly before spending a dollar on ads.",
    features: [
      { title: "Campaign Architecture", desc: "Account structure designed for performance — the right match types, negative keywords, and ad group segmentation from day one." },
      { title: "Search Campaigns", desc: "Intent-based search campaigns targeting buyers, not browsers. Copy written to match the search context, not to impress." },
      { title: "Performance Max", desc: "PMax campaigns built with strong asset groups and audience signals — not left to Google's defaults." },
      { title: "Conversion Tracking", desc: "GA4, Google Ads, and server-side tracking set up accurately. You can't optimize what you can't measure." },
      { title: "Creative Testing", desc: "Systematic ad copy and creative testing with statistical significance thresholds. No gut-feel decisions." },
      { title: "Reporting", desc: "Weekly reports focused on business metrics — leads, revenue, ROAS — not vanity metrics." },
    ],
    process: [
      { step: "01", title: "Audit & Setup", desc: "Existing account audit (or new account setup), conversion tracking verification, and baseline measurement." },
      { step: "02", title: "Campaign Build", desc: "Campaign structure, keyword research, ad copy, and landing page alignment." },
      { step: "03", title: "Launch & Learn", desc: "Two-week learning period with daily monitoring. No major changes until the algorithm has sufficient data." },
      { step: "04", title: "Optimize", desc: "Weekly optimization cycles: bid adjustments, negative keywords, creative testing, audience refinement." },
      { step: "05", title: "Scale", desc: "Proven campaigns scaled methodically. Budget increases tied to efficiency thresholds, not ambition." },
    ],
    stats: [
      { value: "Ongoing", label: "Engagement model" },
      { value: "20+", label: "Clients managed" },
      { value: "Monthly", label: "Reporting" },
      { value: "ROAS / CPA", label: "Tracked metrics" },
    ],
    faq: [
      { q: "What budget do we need to start?", a: "Minimum $1,500/month ad spend. Below that, the learning period takes too long to generate meaningful data." },
      { q: "How long until we see results?", a: "The first 4 weeks are the learning period. Meaningful optimization starts in week 5–6. Month 3 is typically when efficiency peaks." },
      { q: "Do you work with existing campaigns?", a: "Yes. We audit first, identify the biggest losses, and fix those before building new campaigns." },
      { q: "Is the management fee separate from ad spend?", a: "Yes. You pay Google directly for ad spend. Our management fee is separate and covers strategy, setup, and optimization." },
    ],
    tools: ["Google Ads", "GA4", "Google Tag Manager", "Looker Studio", "Search Console", "SEMrush"],
    relatedServices: ["seo-geo", "web-design", "web-app"],
  },
  {
    n: "07",
    slug: "seo-geo",
    title: "SEO & GEO",
    cat: "Growth",
    desc: "Technical SEO plus generative-engine optimization — being found by Google and by models.",
    items: ["Technical · Content", "Schema · Core Web Vitals", "LLM citation surfaces"],
    longDesc:
      "SEO in 2025 means being found by both search engines and language models. We handle technical SEO — Core Web Vitals, schema markup, crawlability — and generative engine optimization: structuring your content so it's cited by Claude, ChatGPT, and Perplexity. These are different problems with different solutions, and we address both.",
    features: [
      { title: "Technical SEO Audit", desc: "Crawl analysis, Core Web Vitals, indexation issues, duplicate content, and redirect chains. Everything that affects how Google sees your site." },
      { title: "Schema Markup", desc: "Structured data that tells search engines exactly what your content is — Organization, Product, Article, FAQ, and custom schemas." },
      { title: "Core Web Vitals", desc: "LCP, INP, and CLS optimization at the code level. We work with your dev team to implement, not just report." },
      { title: "Content Strategy", desc: "Topic cluster mapping, content gap analysis, and editorial calendar built around search intent, not just volume." },
      { title: "GEO (Generative Engine)", desc: "Structuring content so language models can accurately cite and summarize it. A different discipline from traditional SEO." },
      { title: "LLM Citation Surfaces", desc: "Building the authoritative content, structured data, and link profile that makes models choose you as a source." },
    ],
    process: [
      { step: "01", title: "Technical Audit", desc: "Full crawl, Core Web Vitals measurement, and indexation analysis. Prioritized fix list with effort/impact estimates." },
      { step: "02", title: "Fix Implementation", desc: "Technical fixes implemented alongside your dev team. We write the specs; we can implement too if needed." },
      { step: "03", title: "Content Map", desc: "Topic clusters, content gaps, and a 6-month editorial calendar tied to search intent and business goals." },
      { step: "04", title: "GEO Layer", desc: "Schema markup, structured content formats, and authority-building content specifically for LLM citation." },
      { step: "05", title: "Monitor & Iterate", desc: "Monthly reporting on rankings, traffic, and citation mentions. Strategy adjusted as the landscape evolves." },
    ],
    stats: [
      { value: "3–6 mos", label: "Typical payoff window" },
      { value: "12+", label: "Sites optimized" },
      { value: "Technical + content", label: "Scope" },
      { value: "Monthly", label: "Reporting" },
    ],
    faq: [
      { q: "What's GEO and why does it matter?", a: "Generative Engine Optimization is the practice of making your content citable by AI models. As more users get answers from AI, being cited by Claude or ChatGPT becomes as important as ranking on Google." },
      { q: "How long does SEO take?", a: "Technical fixes show results in 2–4 weeks. Content impact takes 3–6 months. GEO results are harder to measure but typically visible in 2–3 months." },
      { q: "Do you write the content?", a: "We can write, brief, or review. Most clients have their own writers and use us for strategy and optimization." },
      { q: "Can you work with our existing CMS?", a: "Yes. We've optimized content on WordPress, Contentful, Sanity, Webflow, and custom setups. Schema and meta implementation adapts to your stack." },
    ],
    tools: ["Screaming Frog", "Ahrefs", "Search Console", "GA4", "PageSpeed Insights", "Schema.org", "Surfer"],
    relatedServices: ["google-ads", "web-design", "web-app"],
  },
  {
    n: "08",
    slug: "how-to-do",
    title: "How To Do?",
    cat: "Teach",
    desc: "Uygulamalı eğitimler, workshoplar ve mentorluk — ekibinizi bağımsız hale getiriyoruz.",
    items: ["Workshop · Eğitim", "1:1 Mentorluk", "Video Eğitim İçerikleri"],
    longDesc:
      "Yazılım, tasarım ve dijital pazarlama alanlarında uygulamalı eğitimler veriyoruz. Teorik değil, pratik odaklı: gerçek projeler üzerinde, gerçek araçlarla, ekibinizin ihtiyacına göre özelleştirilmiş müfredat. Amacımız bize bağımlılık yaratmak değil — ekibinizi bağımsız ve yetkin hale getirmek.",
    features: [
      { title: "Uygulamalı Workshoplar", desc: "Yarım gün veya tam gün formatında ekip workshopları. Gerçek projeler üzerinde, canlı kodlama ve tasarım ile ilerliyor." },
      { title: "1:1 Mentorluk", desc: "Bireysel gelişim için kişiye özel mentorluk. Kendi projeniz üzerinde, kendi sorunlarınızla çalışıyoruz." },
      { title: "Video Eğitim Serisi", desc: "Adım adım video eğitimler — Next.js, React, Supabase, AI entegrasyonu, SEO ve daha fazlası." },
      { title: "AI ile Geliştirme", desc: "Claude Code, Cursor ve AI araçlarıyla nasıl 5 kat hızlı geliştirme yapılır — ilk repo'dan production'a." },
      { title: "Ekip Playbook'ları", desc: "Ekibinizin teknolojilerine özel yazılmış dahili dokümantasyon, workflow kuralları ve best practice rehberleri." },
      { title: "Sürekli Danışmanlık", desc: "Aylık check-in'ler ile ekibin gelişimini takip ediyor, tıkanma noktalarını çözüyor, yeni pattern'ler öğretiyoruz." },
    ],
    process: [
      { step: "01", title: "İhtiyaç Analizi", desc: "Ekibin mevcut beceri seviyesi, kullandığı araçlar ve hedefler belirleniyor. Eğitim müfredatı buna göre tasarlanıyor." },
      { step: "02", title: "Müfredat Tasarımı", desc: "Gerçek projenize ve tech stack'inize uygun egzersizler ve workshop içerikleri hazırlanıyor." },
      { step: "03", title: "Eğitim Sunumu", desc: "Canlı, uygulamalı session. Herkes session sonunda gerçek bir şey teslim etmiş oluyor." },
      { step: "04", title: "Dokümantasyon", desc: "Eğitim sonrası ekibinize özel pattern'ler, convention'lar ve referans kartları yazılıyor." },
      { step: "05", title: "Takip & Mentorluk", desc: "Eğitim sonrası bireysel derinleşme isteyenler için opsiyonel 1:1 mentorluk session'ları." },
    ],
    stats: [
      { value: "1–3 days", label: "Typical duration" },
      { value: "8+", label: "Organizations trained" },
      { value: "Hands-on", label: "Session format" },
      { value: "Recording + materials", label: "Deliverables" },
    ],
    faq: [
      { q: "Hangi konularda eğitim veriyorsunuz?", a: "Web geliştirme (Next.js, React), AI araçları (Claude Code, Cursor), veritabanı (Supabase, PostgreSQL), SEO, otomasyon ve dijital pazarlama. İhtiyaca göre özelleştiriyoruz." },
      { q: "Online eğitim veriyor musunuz?", a: "Evet. Online workshoplar 12 kişiye kadar çok iyi çalışıyor. Daha büyük gruplar için yüz yüze eğitimi öneriyoruz." },
      { q: "Eğitim için minimum seviye gerekli mi?", a: "Konuya göre değişir. Teknik eğitimler için temel programlama bilgisi yeterli. Pazarlama eğitimleri herkes için açık." },
      { q: "ROI'yi nasıl ölçüyoruz?", a: "Eğitim öncesi ve sonrası sprint velocity, teslim kalitesi ve ekip memnuniyeti ölçüyoruz. Çoğu ekip 3-5× verimlilik artışı raporluyor." },
    ],
    tools: ["Claude Code", "Claude", "Next.js", "React", "TypeScript", "Supabase", "Figma", "VS Code", "Cursor", "Python", "Vercel"],
    relatedServices: ["ai-integration", "web-app", "web-design"],
  },
  {
    n: "09",
    slug: "data-engineering",
    title: "Data Engineering",
    cat: "Data",
    desc: "Warehouses, ELT pipelines, and analytics layers your team can actually query.",
    items: ["Postgres · BigQuery", "dbt · Airbyte · Airflow", "Metrics · dashboards"],
    longDesc:
      "We build data infrastructure that your team actually uses — clean schemas, reliable pipelines, and dashboards that answer real questions. From raw event streams to executive dashboards, we handle the full analytics stack. The goal is a data warehouse your team trusts enough to make decisions from.",
    features: [
      { title: "Warehouse Design", desc: "Dimensional modeling in BigQuery, Snowflake, or Postgres. Schemas designed for both query performance and team usability." },
      { title: "ELT Pipelines", desc: "Airbyte for extraction, dbt for transformation. Every transformation tested, documented, and version-controlled." },
      { title: "dbt Models", desc: "Modular dbt project with staging, intermediate, and mart layers. Every model has tests and documentation." },
      { title: "Orchestration", desc: "Airflow or Prefect for pipeline scheduling, monitoring, and failure handling. No silent failures." },
      { title: "Metrics Layer", desc: "Semantic layer with consistent metric definitions across all dashboards. One source of truth for 'revenue' and 'active users'." },
      { title: "Dashboards", desc: "Looker, Metabase, or Superset dashboards built around actual business questions, not what the tool makes easy." },
    ],
    process: [
      { step: "01", title: "Data Audit", desc: "Inventory of existing data sources, quality assessment, and identification of the 5 questions the business most needs to answer." },
      { step: "02", title: "Architecture Design", desc: "Warehouse selection, schema design, and pipeline architecture documented before any code." },
      { step: "03", title: "Pipeline Build", desc: "ELT pipelines with data quality checks, alerting, and incremental loading from the start." },
      { step: "04", title: "Transform Layer", desc: "dbt models covering all core business entities with tests and documentation." },
      { step: "05", title: "Dashboard Delivery", desc: "Business dashboards built with stakeholders, not for them. Iteration included." },
    ],
    stats: [
      { value: "8–16 wks", label: "Typical timeline" },
      { value: "Ingest → warehouse → report", label: "Scope" },
      { value: "99.9%", label: "Pipeline target" },
      { value: "Ongoing upkeep", label: "Engagement model" },
    ],
    faq: [
      { q: "Which warehouse should we use?", a: "BigQuery for GCP shops, Snowflake for enterprise, Postgres for early-stage. We'll recommend based on your team size, budget, and existing stack." },
      { q: "We have messy, inconsistent data — can you still help?", a: "That's the typical starting point. Data cleaning and normalization is part of the dbt transformation layer." },
      { q: "Do you train our team on dbt?", a: "Yes. Knowledge transfer is part of every engagement. We don't build black boxes." },
      { q: "How do you handle PII and data privacy?", a: "Column-level masking, role-based access, and data classification as standard. We can also help with GDPR/CCPA compliance requirements." },
    ],
    tools: ["BigQuery", "PostgreSQL", "Python", "SQL", "dbt", "Airbyte", "Airflow", "Prefect", "Looker", "Metabase", "Supabase"],
    relatedServices: ["ai-integration", "automation", "cloud-ecosystem"],
  },
  {
    n: "10",
    slug: "cloud-ecosystem",
    title: "Cloud Ecosystem",
    cat: "Infra",
    desc: "Production-grade cloud setups across Google Cloud and Vercel — observable, documented, handover-ready.",
    items: ["Google Cloud · Vercel", "IaC · Terraform", "CI/CD · monitoring"],
    longDesc:
      "We design and build cloud infrastructure that's production-ready from day one — not just something that works, but something observable, documented, and safe to hand over. Google Cloud for backend infrastructure, Vercel for frontend deployment, Terraform for infrastructure-as-code, and a monitoring stack that tells you what's happening before users notice it isn't.",
    features: [
      { title: "Infrastructure as Code", desc: "Terraform modules for all infrastructure. Everything reproducible, version-controlled, and reviewable." },
      { title: "Google Cloud Architecture", desc: "Cloud Run, GKE, Cloud SQL, Cloud Storage, Cloud CDN — Google's managed services right-sized for your workload." },
      { title: "Vercel Deployment", desc: "Edge-optimized frontend hosting with preview deployments, ISR, and serverless functions — the fastest path from commit to production." },
      { title: "CI/CD Pipelines", desc: "GitHub Actions workflows with automated testing, preview deployments, and controlled production releases." },
      { title: "Monitoring Stack", desc: "Google Cloud Monitoring, Grafana, or Datadog configured to alert on what matters. Dashboards your on-call team will actually use." },
      { title: "Documentation", desc: "Architecture decision records, runbooks, and incident response playbooks. Your team can operate it after we leave." },
    ],
    process: [
      { step: "01", title: "Architecture Review", desc: "Current state assessment, bottleneck identification, and future-state architecture design with tradeoffs documented." },
      { step: "02", title: "IaC Migration", desc: "Existing infrastructure codified in Terraform. No more click-ops." },
      { step: "03", title: "CI/CD Build", desc: "Automated pipelines for all environments — dev, staging, production — with deployment gates and rollback procedures." },
      { step: "04", title: "Monitoring Setup", desc: "Alerts, dashboards, and on-call runbooks configured and tested before go-live." },
      { step: "05", title: "Handover", desc: "Documentation package, team training session, and 30-day support window." },
    ],
    stats: [
      { value: "4–10 wks", label: "Typical timeline" },
      { value: "6+", label: "Setups delivered" },
      { value: "99.9%", label: "Uptime target" },
      { value: "Vercel / GCP", label: "Stack used" },
    ],
    faq: [
      { q: "Why Google Cloud over AWS?", a: "Google Cloud offers superior managed services, better pricing models, and tighter integration with AI/ML tooling. For most workloads we handle, GCP + Vercel is the optimal combination." },
      { q: "Do you manage the infrastructure ongoing?", a: "We set up and hand over. Ongoing management retainers are available but most clients prefer to own their infrastructure after we've set it up well." },
      { q: "How do you handle disaster recovery?", a: "RTO and RPO targets defined in the architecture phase, with tested recovery procedures. DR isn't an afterthought." },
      { q: "Do you work with Kubernetes?", a: "Yes. GKE on Google Cloud or self-managed. We'll recommend it when the complexity is justified — which is less often than people think." },
    ],
    tools: ["Google Cloud", "Vercel", "Supabase", "Terraform", "GitHub Actions", "Docker", "Kubernetes", "PostgreSQL", "Python", "Next.js", "Clerk", "Datadog", "Grafana"],
    relatedServices: ["web-app", "data-engineering", "automation"],
  },
  {
    n: "11",
    slug: "agentic-ai",
    title: "Agentic AI",
    cat: "Agentic",
    desc: "Autonomous AI agents that handle multi-step business workflows end-to-end.",
    items: ["Autonomous Agents", "Tool-use & API Orchestration", "Human-in-the-loop Design"],
    longDesc: "We build autonomous AI agents that plan, execute, and iterate on complex business tasks — from customer support to data pipelines — with built-in guardrails and observability.",
    features: [
      { title: "Agent Architecture", desc: "Multi-step agents with memory, tool-use, and planning capabilities." },
      { title: "Workflow Automation", desc: "Replace manual multi-step processes with autonomous agent pipelines." },
      { title: "Guardrails & Safety", desc: "Built-in content filtering, rate limiting, and human approval gates." },
      { title: "Tool Integration", desc: "Connect agents to APIs, databases, and external services seamlessly." },
      { title: "Observability", desc: "Full trace logging, cost tracking, and performance dashboards." },
      { title: "Evaluation & Testing", desc: "Automated evals to measure agent accuracy and catch regressions." },
    ],
    process: [
      { step: "01", title: "Discovery", desc: "Map existing workflows and identify automation candidates." },
      { step: "02", title: "Architecture", desc: "Design agent topology, tool integrations, and safety layers." },
      { step: "03", title: "Build", desc: "Implement agents with iterative testing against real scenarios." },
      { step: "04", title: "Deploy", desc: "Production rollout with monitoring and alerting." },
      { step: "05", title: "Optimize", desc: "Continuous improvement based on production metrics and feedback." },
    ],
    stats: [
      { value: "6–12 wks", label: "Typical timeline" },
      { value: "Tool-using agents", label: "Scope" },
      { value: "Human-approved", label: "Control model" },
      { value: "24/7", label: "Runs continuously" },
    ],
    faq: [
      { q: "What tasks can AI agents automate?", a: "Customer support, data processing, content generation, research, reporting, and multi-step business workflows." },
      { q: "How do you ensure agent reliability?", a: "Guardrails, human-in-the-loop gates, automated evaluations, and comprehensive logging." },
      { q: "Which LLMs do you use?", a: "Claude, GPT-4, Gemini — we pick the best model for each use case and budget." },
      { q: "How long does implementation take?", a: "MVP agents typically ship in 2-4 weeks, with iterative improvements after launch." },
    ],
    tools: ["Claude", "OpenAI", "LangChain", "Supabase", "Python", "TypeScript", "Vercel AI SDK"],
    relatedServices: ["ai-integration", "automation", "ai-consulting"],
  },
  {
    n: "12",
    slug: "ai-consulting",
    title: "AI Consulting",
    cat: "Agentic",
    desc: "AI strategy advisory — identify where AI creates real value in your business.",
    items: ["Strategy & Roadmap", "Use Case Analysis", "Build vs Buy Guidance"],
    longDesc: "We help businesses cut through the AI hype and find the use cases that actually move the needle. Strategy, vendor evaluation, and implementation roadmaps.",
    features: [
      { title: "AI Readiness Audit", desc: "Assess your data, infrastructure, and team readiness for AI adoption." },
      { title: "Use Case Mapping", desc: "Identify high-impact AI opportunities across your business processes." },
      { title: "Vendor Evaluation", desc: "Compare LLM providers, tools, and platforms for your specific needs." },
      { title: "ROI Modeling", desc: "Build business cases with realistic cost and impact projections." },
      { title: "Implementation Roadmap", desc: "Phased plan from proof-of-concept to production rollout." },
      { title: "Risk Assessment", desc: "Identify regulatory, ethical, and technical risks before you build." },
    ],
    process: [
      { step: "01", title: "Intake", desc: "Understand your business, goals, and current tech landscape." },
      { step: "02", title: "Audit", desc: "Deep dive into data assets, workflows, and team capabilities." },
      { step: "03", title: "Strategy", desc: "Deliver prioritized AI use cases with ROI estimates." },
      { step: "04", title: "Roadmap", desc: "Create a phased implementation plan with milestones." },
      { step: "05", title: "Handoff", desc: "Detailed documentation, vendor recommendations, and next steps." },
    ],
    stats: [
      { value: "2–4 wks", label: "Typical engagement" },
      { value: "8+", label: "Companies advised" },
      { value: "Roadmap", label: "Deliverable" },
      { value: "Build support", label: "Follow-through" },
    ],
    faq: [
      { q: "Do you also build the AI solution?", a: "Yes — consulting often leads to implementation. We offer end-to-end service from strategy to deployment." },
      { q: "What industries do you serve?", a: "E-commerce, real estate, SaaS, fintech, education, and professional services." },
      { q: "How is this different from AI integration?", a: "Consulting is strategy-first — we help you decide what to build. Integration is the actual building." },
      { q: "What's the minimum engagement?", a: "A focused 2-week sprint covering audit, strategy, and roadmap." },
    ],
    tools: ["Claude", "OpenAI", "Google Cloud AI", "Azure AI", "Notion", "Miro"],
    relatedServices: ["agentic-ai", "ai-integration", "how-to-do"],
  },
];

export function getServiceBySlug(slug: string): Service | undefined {
  return SERVICES.find((s) => s.slug === slug);
}

export function getAllServiceSlugs(): string[] {
  return SERVICES.map((s) => s.slug);
}

export const MANIFESTO =
  "We make cinematic identities for studios that believe pace, restraint, and a little grain still matter.";

export const SCENES: Scene[] = [
  { id: "hero",  label: "Ana Sayfa",    hash: "hero"  },
  { id: "spark", label: "Hemen Başla",  hash: "spark" },
  { id: "work", label: "Projeler", hash: "projects" },
  { id: "note",  label: "Hakkımızda",   hash: "note"  },
  { id: "services", label: "Hizmetler", hash: "services" },
  { id: "process", label: "Süreç", hash: "process" },
  { id: "about", label: "Biz", hash: "about" },
  { id: "contact", label: "İletişim", hash: "contact" },
];

export const STORIES: Story[] = [
  {
    no: "01",
    slug: "dolmus",
    title: "Bozüyük Dolmuşçular Derneği",
    sub: "Minibüs güzergah takip sistemi.",
    year: "2026",
    role: "Full-stack / Design",
    tags: ["Web App", "Transportation", "Mapping"],
    image: "story-01.jpg",
    body: [
      "Toplu taşıma için minibüs güzergah takip sistemi olan Dolmuş web uygulamasını geliştirdik. Kullanıcılar güzergahları kolayca görüntüleyebiliyor ve seyahat planlaması yapabiliyor.",
      "Gerçek zamanlı güzergah bilgisi, kullanıcı dostu arayüz ve mobil uyumlu tasarım ile şehir içi ulaşımı kolaylaştırdık.",
    ],
    client: "Bozüyük Dolmuşçular Derneği",
  },
  {
    no: "02",
    slug: "orchid-tent",
    title: "Orchid Tent",
    sub: "Londra merkezli çadır ve etkinlik kiralama.",
    year: "2025",
    role: "Design / Development",
    tags: ["Corporate", "Events", "London"],
    image: "story-02.jpg",
    body: [
      "Londra merkezli Orchid Tent için çadır ve etkinlik kiralama hizmeti sunan kurumsal bir web sitesi tasarladık. Şık tasarım ve kolay navigasyon ile potansiyel müşterilerin hızlıca bilgi edinmesini sağladık.",
      "Etkinlik galerisi, fiyat teklifi formu ve responsive tasarım ile Londra'daki etkinlik sektöründe güçlü bir dijital varlık oluşturduk.",
    ],
    client: "Orchid Tent",
  },
  {
    no: "03",
    slug: "gabfest-2025",
    title: "Gabfest 2025",
    sub: "Konferans ve etkinlik web sitesi.",
    year: "2025",
    role: "Design / Development",
    tags: ["WordPress", "Event", "Conference"],
    image: "story-03.jpg",
    body: [
      "Gabfest 2025 konferansı için WordPress altyapısında modern ve bilgilendirici bir etkinlik web sitesi tasarladık. Program, konuşmacılar ve kayıt bilgilerini düzenli bir şekilde sunduk.",
      "Etkinlik öncesi, sırası ve sonrasında güncel bilgi akışı sağlayan dinamik bir yapı kurduk. Mobil uyumlu tasarım ile katılımcıların her cihazdan kolayca erişmesini sağladık.",
    ],
    client: "Gabfest",
  },
  {
    no: "04",
    slug: "aydin-transfer",
    title: "Aydın Transfer",
    sub: "Havalimanı ve şehir içi transfer hizmeti.",
    year: "2025",
    role: "Design / Development",
    tags: ["Corporate", "Transfer", "Booking"],
    image: "story-05.jpg",
    body: [
      "Aydın Transfer için havalimanı ve şehir içi transfer hizmeti sunan kurumsal bir web sitesi tasarladık. Kolay rezervasyon akışı, fiyat hesaplama ve iletişim formları ile müşteri deneyimini optimize ettik.",
      "Mobil uyumlu tasarım ve hızlı yüklenme süreleri ile yolcuların her an kolayca transfer rezervasyonu yapabilmesini sağladık.",
    ],
    client: "Aydın Transfer",
  },
  {
    no: "05",
    slug: "cyprokey",
    title: "Cyprokey",
    sub: "Kıbrıs gayrimenkul platformu.",
    year: "2025",
    role: "Design / Development",
    tags: ["Real Estate", "Platform", "KKTC"],
    image: "cyprokey.jpg",
    body: [
      "Cyprokey için Kuzey Kıbrıs gayrimenkul piyasasına yönelik modern bir emlak platformu tasarladık. İlan yönetimi, gelişmiş filtreleme ve harita entegrasyonu ile alıcı ve satıcıları buluşturduk.",
      "SEO optimizasyonu ve kullanıcı dostu arayüz ile emlak aramaları için güçlü bir dijital varlık oluşturduk.",
    ],
    client: "Cyprokey",
  },
  {
    no: "06",
    slug: "salih-defterali",
    title: "Salih Defterali",
    sub: "Kişisel portfolyo ve workstation sitesi.",
    year: "2026",
    role: "Design / Development",
    tags: ["Portfolio", "Personal", "Web Design"],
    image: "reel-b.jpg",
    body: [
      "Salih Defterali için kişisel portfolyo ve çalışma alanı web sitesi tasarladık. Projeleri, yetenekleri ve iş deneyimini sergileyen minimal ve etkileyici bir dijital varlık oluşturduk.",
      "Temiz tipografi, akıcı animasyonlar ve responsive tasarım ile profesyonel bir ilk izlenim oluşturmayı hedefledik.",
    ],
    client: "Salih Defterali",
  },
];
